### ISSUE TITLE
Bad get request convention

### ISSUE THREAD

**Issue by Howon** [ADI-Labs/mixtapes.io#3]
https://github.com/ADI-Labs/mixtapes.io/blob/master/routes/index.js#L14-L21

instead of doing 
```
app.get("/a/b/c")
```
to get a, b and c,
do

```
app.get("/",)
```

and use req.query

http://stackoverflow.com/questions/6912584/how-to-get-get-query-string-variables-in-express-js-on-node-js

**Comment by cesaribarra10** [comment]
we killed that route in a seperate branch, that @kyshim is working on, she'll push on to master and update it
